name: Cleanup Promotion Branches
on:
  pull_request:
    types:
      - closed
jobs:
  cleanup-branch:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'features/auto-promote-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Delete Merged Branch
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
